quarkus:
  http:
    port: 8080

  datasource:
    db-kind: postgresql
    username: superman
    password: superman
    reactive:
      url: postgresql://localhost:8090/heroes_database

  hibernate-orm:
    database:
      generation: drop-and-create
    log:
      sql: true
