quarkus:
  http:
    port: 8083
    test-port: 8084

  datasource:
    db-kind: postgresql
    username: superman
    password: superman
    reactive:
      url: postgresql://localhost:8090/heroes_database

  hibernate-orm:
    database:
      generation: drop-and-create
    log:
      sql: true

#  log:
#    console:
#      enable: true
#      format: "%d{HH:mm:ss} %-5ppom [%c{2.}] (%t) %s%e%n"
#      level: DEBUG
#      color: true

# Business configuration
heroes:
  level:
    multiplier: 3


"%test":
  quarkus:
    datasource:
      db-kind: postgresql
      reactive:
        url: postgresql://localhost:8098/heroes_database
      username: superman
      password: superman
    hibernate-orm:
      database:
        generation: drop-and-create
